### ISSUE TITLE
remove模块建议

### ISSUE THREAD

**Issue by SFTM** [Linxaee/kivibot-plugin-group-manager#2]
remove模块:
    1. /踢 <qq号/@某人> : 将目标移出群聊
    2. /黑 <qq号/@某人> : 将目标移出群聊并拉黑(不再接收入群申请)

踢人指令建议合并，在实际使用的时候，两个指令也很容易被用成1个。
按现有设计可能踢人功能会较鸡肋后续大概率被弃用，常见场景，前脚踢的人，后脚又被自动审批进群了，无奈之下只能使用拉黑。

修改方案参考：
/踢 <qq号/@某人> <时间(h)/永久>: 将目标移出群聊，并在临时拉黑一段时间（默认24h可配置），期间不再同意其加群申请
黑名单加一个字段写时间戳，让黑名单具有时效性。

需要注意的是：黑名单在拒绝加群申请时，拒绝理由最好描述成：申请频繁/加群CD，而不是黑名单。

自主退群也可以考虑设置一个退群重加的CD，也可以用临时黑名单来实现。
之前有些自动化管理的群里会有的人在被禁言后选择退群重加来解禁言（不清楚现在Q群是否还有这个漏洞）

**Comment by Linxaee** [comment]
已修改！感谢建议
