### ISSUE TITLE
加群审批模块修改建议

### ISSUE THREAD

**Issue by SFTM** [Linxaee/kivibot-plugin-group-manager#8]
加群审批功能在申请无法通过时
需要分场景，根据管理需求自定义拒绝方式：
1：忽略
2：拒绝并回复理由
理由文本支持自定义

例：
审批词条出错：拒绝并回复：请正确填写答案（补充提示）
临时黑名单：拒绝并回复：加群冷却中，请24h后再尝试
全局黑名单：忽略

**Comment by Linxaee** [comment]
感谢反馈！
修改情况如下：

1. 审批词条出错时，拒绝并回复：请正确回答入群问题
2. 临时黑名单，拒绝并回复:  加群冷却中,请（冷却时间）后再尝试
3. 群黑名单，拒绝并回复：您已被本群拉黑，请勿重复申请
4. 全局黑名单，拒绝且**不回复**
5. **群黑名单拒绝理由**支持自定义

有以下几点说明：

1. 对于自定义拒绝理由，考虑到尽量维护**配置的简洁性**，暂时不打算对所有情况增加自定义反馈，目前仅支持群黑名单的自定义
2. 至于忽略，考虑到忽略申请会造成**申请堆积**，管理员还需自行分辨申请人是否在黑名单中，所以只要不通过一律拒绝，如果想放行可以解除黑名单
